<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Nombre de usuario</name>
   <tag></tag>
   <elementGuidId>53f22c45-2a7f-4e53-b351-189018d3853f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//label[@id='logUPN_UserNameLabel']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#logUPN_UserNameLabel</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>9c6f618c-f728-4117-94a0-75aa4788dd36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>logUPN_UserName</value>
      <webElementGuid>d066d310-a608-4e10-a087-391feeb512f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>logUPN_UserNameLabel</value>
      <webElementGuid>686b7820-1e66-4965-8e20-c4c1beb2b3bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Nombre de usuario:</value>
      <webElementGuid>36e72b49-7f28-483c-9edb-cc835e4d6d16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;logUPN_UserNameLabel&quot;)</value>
      <webElementGuid>84ff466e-34f7-440c-bc12-b93c3122656e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@id='logUPN_UserNameLabel']</value>
      <webElementGuid>2958f601-bf6d-4799-8620-d041e4009233</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='logUPN']/tbody/tr/td/div[2]/label</value>
      <webElementGuid>d2dd3a96-63d4-48fe-925d-650857a6544c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Iniciar sesión'])[1]/following::label[1]</value>
      <webElementGuid>2fd9a110-9873-41fc-ae7b-323fbd02df3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bienvenidos al portal de administración web, por favor introduzca sus datos de acceso'])[1]/following::label[1]</value>
      <webElementGuid>4b6e031c-11b0-44cf-a48f-a748c4f28f07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[1]/preceding::label[1]</value>
      <webElementGuid>b91f7684-0632-4d6d-bfdb-5295307768f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contraseña:'])[1]/preceding::label[1]</value>
      <webElementGuid>ef9fd55d-7d1b-44e9-a944-224d4312cde0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Nombre de usuario:']/parent::*</value>
      <webElementGuid>3d308241-ce9f-458f-9954-621082899131</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label</value>
      <webElementGuid>52742277-285b-46fd-95b4-4a71cc3aad50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@id = 'logUPN_UserNameLabel' and (text() = 'Nombre de usuario:' or . = 'Nombre de usuario:')]</value>
      <webElementGuid>0448542d-7869-4cfb-aa48-b9d2b2f6c7a2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
