<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Se requiere JavaScript_Password</name>
   <tag></tag>
   <elementGuidId>15c6b54a-b977-4126-8afb-03e95b22d095</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='passwordInput']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#passwordInput</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>978dca9a-6e62-42fc-95af-0e176ada63a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>passwordInput</value>
      <webElementGuid>246e0b6b-0b15-48f4-87d5-35a872cad2e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Password</value>
      <webElementGuid>378d256f-acf0-4495-9395-7b2624095604</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>5b03b819-9362-4ce1-a4a8-2b891fc33a61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>1bba0780-082c-4697-8161-af19b1d745f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text fullWidth</value>
      <webElementGuid>e839a26e-12f4-4ecf-948d-b9449306b2d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Contraseña</value>
      <webElementGuid>d7e6a902-ef8d-4de6-b096-9e42cc0c850f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>c1d913f7-517f-4ec6-bd90-1a94b9d710e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;passwordInput&quot;)</value>
      <webElementGuid>7efa3390-24eb-4783-bbcb-a77a4aad9f87</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='passwordInput']</value>
      <webElementGuid>4faf41fd-ccab-49b1-8989-dfc11eddb4f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='passwordArea']/input</value>
      <webElementGuid>a5103a54-c50d-4bde-8db6-c9829acab799</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Se requiere JavaScript'])[1]/following::input[2]</value>
      <webElementGuid>0b108c09-2ab8-4ec7-8bc4-a3f6ef05053c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mantener la sesión iniciada'])[1]/preceding::input[2]</value>
      <webElementGuid>7846e9ef-8073-4c6c-87d6-031bf20d2d95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Iniciar sesión'])[2]/preceding::input[2]</value>
      <webElementGuid>a57f9fff-ec64-488e-be24-d9be5606e942</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>72b40bc9-d132-445b-9dd8-91ac8a5679fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'passwordInput' and @name = 'Password' and @type = 'password' and @placeholder = 'Contraseña']</value>
      <webElementGuid>e585bcab-e752-4019-a8f0-863c88f5cb4a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
