<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Aula Virtual</name>
   <tag></tag>
   <elementGuidId>c8fa0e33-e188-4623-ad2c-ec7909ad8af8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='medium-contenedor']/li[2]/a/div/p</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>7735cbdb-ed2f-4474-ab23-0141c9e36c8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Aula Virtual</value>
      <webElementGuid>c7d5b7df-7dca-4532-adf1-f82ebc40c2c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;medium-contenedor&quot;)/li[2]/a[@class=&quot;boton-aplicativo tooltip&quot;]/div[1]/p[1]</value>
      <webElementGuid>23a9fa1f-3167-4f85-ba29-33edec5c1b32</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='medium-contenedor']/li[2]/a/div/p</value>
      <webElementGuid>c226e5bd-0eb6-4d1c-a934-750edb01f875</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Logout'])[1]/following::p[2]</value>
      <webElementGuid>e6298a33-b009-455d-bcbf-7e268b1c547c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Roger Villar Morales'])[1]/following::p[2]</value>
      <webElementGuid>4e3d32a9-1a73-4980-8ea5-af09e56544be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ocultar Banners'])[1]/preceding::p[13]</value>
      <webElementGuid>e1cf8d9c-a505-4b40-a1ec-99cb1b14e51f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mi Mundo UPN'])[1]/preceding::p[13]</value>
      <webElementGuid>f4712051-0d57-4f0f-993a-a41ac6899d67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/a/div/p</value>
      <webElementGuid>73f78a27-3e58-4a59-a957-4de24d9c9157</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Aula Virtual' or . = 'Aula Virtual')]</value>
      <webElementGuid>23f202f5-78d1-4b25-9596-47196f9a0c44</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
