<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_video_btnLoginDocente</name>
   <tag></tag>
   <elementGuidId>57096e97-f02e-4aa8-83a5-77b07fbb4cd3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='btnLoginDocente']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#btnLoginDocente</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>23d922e9-6726-425e-8bb6-abd0960308d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>c7a4bc9d-f43b-42a6-9e55-2b51be7312e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>btnLoginDocente</value>
      <webElementGuid>d8423e8d-a4bd-400c-8577-3b1b341c1036</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Docentes</value>
      <webElementGuid>12058ba3-9531-4339-adee-2adfbe45c6f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnLoginDocente</value>
      <webElementGuid>304932aa-b51b-4ff3-bf22-be378a9046e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button-submit</value>
      <webElementGuid>21a7b3ed-5e5d-40ed-af1e-638197ad9a34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnLoginDocente&quot;)</value>
      <webElementGuid>2b7e4d8c-42e3-443b-bacc-ebd354bd8a67</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='btnLoginDocente']</value>
      <webElementGuid>6dfb0a57-60a3-49f9-8c9f-be8b02720695</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='logUPN3']/div/div/input</value>
      <webElementGuid>db03c6cc-0baf-4907-bc01-1457e59dd731</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/input</value>
      <webElementGuid>3954f8fe-2de4-4660-a264-446737b8b5bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @name = 'btnLoginDocente' and @id = 'btnLoginDocente']</value>
      <webElementGuid>b931e39d-fd79-4010-b924-ad592efe4c26</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
