<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_NOTIFICACIN_new_menu_services_class p-1</name>
   <tag></tag>
   <elementGuidId>b3da4594-a1d6-45a5-9b8b-0c2c27a3ab8c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='navbarSupportedContent']/div/ng-component/div/div/nav/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.new_menu_services_class.p-1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c2d0a64f-5129-4545-ac6f-3bbd810ae122</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>new_menu_services_class p-1</value>
      <webElementGuid>7badf03d-f05c-428d-a579-e843bec88544</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;navbarSupportedContent&quot;)/div[@class=&quot;col-auto c0026&quot;]/ng-component[1]/div[@class=&quot;main_div_menu&quot;]/div[@class=&quot;new_menu_services_type_main_div&quot;]/nav[@class=&quot;navbar navbar-expand-lg navbar-dark  ms-2&quot;]/div[@class=&quot;new_menu_services_class p-1&quot;]</value>
      <webElementGuid>44a344c6-a027-4eb2-a61a-18d153787c6f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='navbarSupportedContent']/div/ng-component/div/div/nav/div</value>
      <webElementGuid>e1ee2074-ed2d-49ec-9253-e3632cb17554</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NOTIFICACIÓN'])[1]/preceding::div[11]</value>
      <webElementGuid>4879c18e-f1da-486a-bcc5-bb3fd94148c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jonathan Michael Solier Prado'])[1]/preceding::div[19]</value>
      <webElementGuid>572aebaf-0da9-4fcd-8ae9-c0480d0ee682</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/nav/div</value>
      <webElementGuid>555e6532-94a0-41ca-8841-1c3ea0ff9490</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
