<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>5404d47b-d270-49ae-b690-a348605ac722</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='navbarSupportedContent']/div/ng-component/div/div/nav/div/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>e320e48f-0489-4d8d-b67c-c23fee2a7382</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>32</value>
      <webElementGuid>bdd085e1-6546-4021-9640-b8d7bcb9d183</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>32</value>
      <webElementGuid>80adb0cb-2491-4894-a291-ad3cf43c9921</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>assets/images/modules/menu button_icon.png</value>
      <webElementGuid>c20c242e-e09a-422a-8d40-a512ed70d0d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;navbarSupportedContent&quot;)/div[@class=&quot;col-auto c0026&quot;]/ng-component[1]/div[@class=&quot;main_div_menu&quot;]/div[@class=&quot;new_menu_services_type_main_div&quot;]/nav[@class=&quot;navbar navbar-expand-lg navbar-dark  ms-2&quot;]/div[@class=&quot;new_menu_services_class p-1&quot;]/div[1]/img[1]</value>
      <webElementGuid>be5f7e44-697e-428a-96e3-c91fd73ab21d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='navbarSupportedContent']/div/ng-component/div/div/nav/div/div/img</value>
      <webElementGuid>6c4d1152-87e0-4fe1-9f11-32a9d096c5d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>a536776c-3ddc-40a6-886b-cca7bbb37dc3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'assets/images/modules/menu button_icon.png']</value>
      <webElementGuid>6b89a72d-48d3-4e69-b86c-fc8d9285d0b7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
