<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_CURSO</name>
   <tag></tag>
   <elementGuidId>f3b1dc3f-d192-455b-9024-e5ee8aacbe10</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='navbarSupportedContent']/div/ng-component/div/div[2]/div[2]/div/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>d6267daf-28dd-4b39-a9c6-99386ea74c02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pointer c00653</value>
      <webElementGuid>cac93b2e-777f-4392-a724-f43ed09393df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> CURSO </value>
      <webElementGuid>1dc882da-8f5f-4659-875c-3bcef7d41dbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;navbarSupportedContent&quot;)/div[@class=&quot;col-auto c0026&quot;]/ng-component[1]/div[@class=&quot;main_div_menu&quot;]/div[@class=&quot;c00669&quot;]/div[@class=&quot;submenulis&quot;]/div[@class=&quot;title_liat_mennu&quot;]/div[@class=&quot;check_Option_menu&quot;]/div[@class=&quot;pointer c00653&quot;]</value>
      <webElementGuid>302c78cb-38fd-4208-b318-1cd0e181f855</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='navbarSupportedContent']/div/ng-component/div/div[2]/div[2]/div/div/div</value>
      <webElementGuid>a3caf558-96ee-4eeb-8b09-941365a666a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Inicio'])[1]/following::div[5]</value>
      <webElementGuid>93eecea0-77b4-4746-b9b9-75bee2385843</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Notas'])[1]/preceding::div[2]</value>
      <webElementGuid>92ded219-cf5a-4a61-b0ef-b6e8eb241bf7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Documentos'])[1]/preceding::div[7]</value>
      <webElementGuid>ada41596-948a-4f95-86cb-3470b88a56d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='CURSO']/parent::*</value>
      <webElementGuid>ce0b07a7-e041-42b3-8acc-298bd2ef847d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/div</value>
      <webElementGuid>6ee78c7e-791f-4da2-bb33-afbabffe001b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = ' CURSO ' or . = ' CURSO ')]</value>
      <webElementGuid>9e6ab4fc-57c0-442e-ac75-0e40f6104a29</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
