<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>1adfc770-09cb-42ff-8e03-9f1f4f765bd9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='navbarSupportedContent']/div/ng-component/div/div/nav/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>e99854e6-0546-433e-9c1f-6edac85d2e26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>32</value>
      <webElementGuid>50dce25a-77d1-483a-ab09-4478b81e7974</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>32</value>
      <webElementGuid>5363fcac-3f75-47c1-b37e-d268c06f611d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>assets/images/modules/menu button_icon.png</value>
      <webElementGuid>9002c234-897b-4255-915c-4b5f7dbea319</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;navbarSupportedContent&quot;)/div[@class=&quot;col-auto c0026&quot;]/ng-component[1]/div[@class=&quot;main_div_menu&quot;]/div[@class=&quot;new_menu_services_type_main_div&quot;]/nav[@class=&quot;navbar navbar-expand-lg navbar-dark  ms-2&quot;]/div[@class=&quot;new_menu_services_class p-1&quot;]/div[1]/img[1]</value>
      <webElementGuid>3e7ab805-73f7-4475-9e55-abc8277cb906</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='navbarSupportedContent']/div/ng-component/div/div/nav/div/div/img</value>
      <webElementGuid>ada93c54-ab29-4bb6-b9aa-52ec6c3f2a2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>f4d22e8d-c7b5-45f2-919e-0c9f128431a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'assets/images/modules/menu button_icon.png']</value>
      <webElementGuid>6a845b07-68f8-4a39-83b4-be8b70f0e371</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
