<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Mis Documentos_img-fluid rounded_img im_f47371</name>
   <tag></tag>
   <elementGuidId>2c448c90-127d-438a-9cba-5e1368ffdf5e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[contains(@src,'https://pe-upn-prod-cmsv4.s3.amazonaws.com/pagos_en_linea_1617659362_a24ab09594.png')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>5cddefdc-828e-4952-9832-65bdb9b54fdc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>img-fluid rounded_img img_service c00809</value>
      <webElementGuid>09c9cc9e-4135-4e3d-a5dd-d76b6f229b40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://pe-upn-prod-cmsv4.s3.amazonaws.com/pagos_en_linea_1617659362_a24ab09594.png</value>
      <webElementGuid>a4576ca5-c163-4d82-8fc5-774aff696100</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/moo-app[1]/div[@class=&quot;main-container&quot;]/section[1]/moo-dashboard-main[1]/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-8 h-100 p-0&quot;]/div[1]/div[@class=&quot;row m-4&quot;]/div[@class=&quot;col h-100 p-0&quot;]/div[1]/ng-component[1]/moo-myservices-dash-widget[1]/div[@class=&quot;row justify-content-md-center services-dash-widget-container&quot;]/div[@class=&quot;my-services-dash-widget-box col cursor-pointer c00805&quot;]/div[1]/div[@class=&quot;d-flex justify-content-center img_container c00829&quot;]/img[@class=&quot;img-fluid rounded_img img_service c00809&quot;]</value>
      <webElementGuid>4670fae3-4257-4954-9c3f-d235dda3168a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://pe-upn-prod-cmsv4.s3.amazonaws.com/pagos_en_linea_1617659362_a24ab09594.png')]</value>
      <webElementGuid>6effe2b6-90cc-4327-a269-00d7f86b93e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/img</value>
      <webElementGuid>119f12a3-b9c4-4f42-8241-80309edf5f85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://pe-upn-prod-cmsv4.s3.amazonaws.com/pagos_en_linea_1617659362_a24ab09594.png']</value>
      <webElementGuid>44788e36-7856-4855-a61f-30a8205cdaeb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
