<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_VER TODOS_img-fluid rounded_img img_ser_bae34f</name>
   <tag></tag>
   <elementGuidId>ddbaf27e-f29a-40a4-af04-0fff6c76d887</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.img-fluid.rounded_img.img_service.c00809</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[contains(@src,'https://pe-upn-prod-cmsv4.s3.amazonaws.com/matricula_en_linea_1617654068_58a74fdd85.png')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>cb65c575-18a7-4d1e-8e65-f6eb5cad0cc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>img-fluid rounded_img img_service c00809</value>
      <webElementGuid>11d8ff5c-1e15-45df-99a1-69281f204349</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://pe-upn-prod-cmsv4.s3.amazonaws.com/matricula_en_linea_1617654068_58a74fdd85.png</value>
      <webElementGuid>5aefc5d2-a937-4c72-834a-be4d4d8b2e8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/moo-app[1]/div[@class=&quot;main-container&quot;]/section[1]/moo-dashboard-main[1]/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-8 h-100 p-0&quot;]/div[1]/div[@class=&quot;row m-4&quot;]/div[@class=&quot;col h-100 p-0&quot;]/div[1]/ng-component[1]/moo-myservices-dash-widget[1]/div[@class=&quot;row justify-content-md-center services-dash-widget-container&quot;]/div[@class=&quot;my-services-dash-widget-box col cursor-pointer c00805&quot;]/div[1]/div[@class=&quot;d-flex justify-content-center img_container c00829&quot;]/img[@class=&quot;img-fluid rounded_img img_service c00809&quot;]</value>
      <webElementGuid>2d4de2f1-d15c-439d-9d14-45b53740c76e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://pe-upn-prod-cmsv4.s3.amazonaws.com/matricula_en_linea_1617654068_58a74fdd85.png')]</value>
      <webElementGuid>2e11d3cc-9cdd-46c5-bd54-56e345552a71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/img</value>
      <webElementGuid>495376b0-5e22-4ae1-a406-2ddacfa32658</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://pe-upn-prod-cmsv4.s3.amazonaws.com/matricula_en_linea_1617654068_58a74fdd85.png']</value>
      <webElementGuid>7f55acba-b555-4966-a4ed-21a996893982</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
