<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Gestor de Tesis_img-fluid rounded_img i_10c4cb</name>
   <tag></tag>
   <elementGuidId>71c25703-df98-4789-8d9c-83f2351ceeef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[contains(@src,'https://pe-upn-prod-cmsv4.s3.amazonaws.com/mis_documentos_67bde82c01.png')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>39fa29b0-2170-423f-ba3b-80f861c3678e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>img-fluid rounded_img img_service c00809</value>
      <webElementGuid>14eb4e7d-009c-47d9-830f-9d2d002d4ba4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://pe-upn-prod-cmsv4.s3.amazonaws.com/mis_documentos_67bde82c01.png</value>
      <webElementGuid>48153ee8-f2b9-4a33-9d57-361b74eb1cdf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/moo-app[1]/div[@class=&quot;main-container&quot;]/section[1]/moo-dashboard-main[1]/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-8 h-100 p-0&quot;]/div[1]/div[@class=&quot;row m-4&quot;]/div[@class=&quot;col h-100 p-0&quot;]/div[1]/ng-component[1]/moo-myservices-dash-widget[1]/div[@class=&quot;row justify-content-md-center services-dash-widget-container&quot;]/div[@class=&quot;my-services-dash-widget-box col cursor-pointer c00805&quot;]/div[1]/div[@class=&quot;d-flex justify-content-center img_container c00829&quot;]/img[@class=&quot;img-fluid rounded_img img_service c00809&quot;]</value>
      <webElementGuid>aa892b00-deeb-4bc7-9c9a-348c761bf277</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://pe-upn-prod-cmsv4.s3.amazonaws.com/mis_documentos_67bde82c01.png')]</value>
      <webElementGuid>6f2241d8-b99e-4bb3-b984-e0526b112b88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/img</value>
      <webElementGuid>e0824d13-5684-4e30-a6f5-f6bdc258a781</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://pe-upn-prod-cmsv4.s3.amazonaws.com/mis_documentos_67bde82c01.png']</value>
      <webElementGuid>c8c6fae2-0635-44b1-9d53-6014afc9caeb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
