<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h5_Pgina Principal</name>
   <tag></tag>
   <elementGuidId>d6b52cdf-89ff-45a0-8541-d718007fa0b7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='cphSite_UpdatePanel1']/h5</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>h5.webmaster-main-header</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h5</value>
      <webElementGuid>06e0559b-b67e-4cba-9ba9-93426706b3a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>webmaster-main-header</value>
      <webElementGuid>8382c99d-e3c7-4b53-abaa-2d92b0770dbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Página Principal</value>
      <webElementGuid>6980df48-d133-4e30-bc59-b87d7cca4d98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cphSite_UpdatePanel1&quot;)/h5[@class=&quot;webmaster-main-header&quot;]</value>
      <webElementGuid>012bcdb0-5854-42e1-be93-6b54808c68ec</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cphSite_UpdatePanel1']/h5</value>
      <webElementGuid>6f76b017-fff1-4322-a2e4-f72e24322b43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Evaluación del desempeño docente'])[1]/following::h5[1]</value>
      <webElementGuid>1c2ed5df-fe3b-43d1-8bd7-c8d76d30e7ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Documentos / Manuales'])[1]/following::h5[1]</value>
      <webElementGuid>7d7a8565-57d9-47bd-b9a8-8c8a10cee0f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Previous'])[1]/preceding::h5[1]</value>
      <webElementGuid>4880be4c-9ceb-402c-ba58-e6dfed1e3034</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Next'])[1]/preceding::h5[1]</value>
      <webElementGuid>2ce88349-2346-456a-a1d4-aa8b9dc083a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Página Principal']/parent::*</value>
      <webElementGuid>714be567-c7da-45ff-8101-dec3c2c3b108</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h5</value>
      <webElementGuid>b44d74ff-6304-439c-aca6-2f5501885bdb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h5[(text() = 'Página Principal' or . = 'Página Principal')]</value>
      <webElementGuid>0b7266f7-4685-44ab-9347-41d9b4caa6b5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
