<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>4ed3d2e1-940d-4e42-844b-a482e2de9731</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='form1']/header/nav/div/div/span/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>c13464e9-9493-45b3-94a9-9d52ae395d36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://upn-repositorio-public.s3.amazonaws.com/logos/png/logo-upn-sin-fondo.png</value>
      <webElementGuid>9c70db44-5290-48eb-be85-06bd036e6cbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>150</value>
      <webElementGuid>5d3aed37-921d-439d-b7b6-d0451a3de799</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form1&quot;)/header[@class=&quot;container mb-1&quot;]/nav[@class=&quot;navbar navbar-expand-lg p-0&quot;]/div[@class=&quot;container p-0&quot;]/div[@class=&quot;col-md-3 p-0 d-none d-md-block&quot;]/span[@class=&quot;navbar-brand&quot;]/img[1]</value>
      <webElementGuid>866b65a8-5c37-448f-950d-9a3080e9d598</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form1']/header/nav/div/div/span/img</value>
      <webElementGuid>26297a4c-f7eb-4fd9-b7fb-09557c8cec6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://upn-repositorio-public.s3.amazonaws.com/logos/png/logo-upn-sin-fondo.png')]</value>
      <webElementGuid>dee033cc-a404-4bab-9177-0473a952f67e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>9357194d-a873-4095-bdf1-07b3d30f207e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://upn-repositorio-public.s3.amazonaws.com/logos/png/logo-upn-sin-fondo.png']</value>
      <webElementGuid>47d5af59-ffff-440a-a8a7-7a601e653985</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
