<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Usuario_logUPNUserName</name>
   <tag></tag>
   <elementGuidId>79178f0e-9ea8-471a-b753-bc18cf2b33d9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='logUPN_UserName']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#logUPN_UserName</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6f435582-27d3-42ca-94e9-b4aff21a0a51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>logUPN$UserName</value>
      <webElementGuid>406559d7-d053-422d-b0bb-5e6947b4cf83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>86de89fa-d6c5-4200-a134-c09ca05c2281</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>logUPN_UserName</value>
      <webElementGuid>2f57e2f5-e75f-4ab2-989f-966883f819e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>textbox-small</value>
      <webElementGuid>7bb0cb13-e407-4bc1-b774-6384b10e0bd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;logUPN_UserName&quot;)</value>
      <webElementGuid>696c3cbe-09a0-41e8-96e3-51fa36a335d7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='logUPN_UserName']</value>
      <webElementGuid>ab50b572-f607-40a3-a9ef-1a8c2e740e9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='logUPN']/tbody/tr/td/div/div/input</value>
      <webElementGuid>fe7da78b-b77a-4dad-956e-75691b0d2f8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/input</value>
      <webElementGuid>9097727b-8a80-4372-8e53-bff73e6db32b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'logUPN$UserName' and @type = 'text' and @id = 'logUPN_UserName']</value>
      <webElementGuid>9840c787-7799-4d24-80e7-dfa0f10a3bf3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
