<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Cambia tu clave aqu_logUPNLoginButton</name>
   <tag></tag>
   <elementGuidId>703c3075-3912-4e74-bf2c-9d8fd4fab20d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='logUPN_LoginButton']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#logUPN_LoginButton</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>734f7c59-2988-4497-9cc3-806e73c5ac5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>e699461c-3a3c-41fe-a983-3b14e74075dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>logUPN$LoginButton</value>
      <webElementGuid>76a32db7-63b8-4bb9-9897-d67d4e1b20d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Iniciar Sesión</value>
      <webElementGuid>868fec9c-4e46-4fc8-9ef8-ce47b0a0caee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:WebForm_DoPostBackWithOptions(new WebForm_PostBackOptions(&quot;logUPN$LoginButton&quot;, &quot;&quot;, true, &quot;logUPN&quot;, &quot;&quot;, false, false))</value>
      <webElementGuid>f27bfcf1-9b92-4f3f-8194-7c816fda2054</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>logUPN_LoginButton</value>
      <webElementGuid>7ad314dd-0a1d-4d01-a993-20df99924e65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button-submit</value>
      <webElementGuid>e15f40d7-f53a-42f2-8979-74bb32b99edc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;logUPN_LoginButton&quot;)</value>
      <webElementGuid>f6ee7bfd-3291-419d-8119-55e1e5f37a70</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='logUPN_LoginButton']</value>
      <webElementGuid>c300bcb7-ecd6-47c5-8bb5-a96f8d77b8a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='logUPN']/tbody/tr/td/div/div[4]/input</value>
      <webElementGuid>f8b2cd07-898c-44cc-91dc-386fffe50b95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/input</value>
      <webElementGuid>d1a699b6-a087-412e-b7ef-eb8dd10a3842</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @name = 'logUPN$LoginButton' and @id = 'logUPN_LoginButton']</value>
      <webElementGuid>023a899b-641e-4aaf-a905-2241d534ec1c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
