<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_video_btnLoginAdmin</name>
   <tag></tag>
   <elementGuidId>e637d1b9-6dd8-4cbf-b0d6-2a86a256970c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='btnLoginAdmin']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#btnLoginAdmin</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3a508e26-58b2-47bc-ad20-1070b567d1e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>091e556c-be57-4456-817e-f62449ddad78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>btnLoginAdmin</value>
      <webElementGuid>0c74c80a-588f-4506-8e61-825a355705aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Administrativos</value>
      <webElementGuid>3dc97f6a-29e3-46b8-8418-e203e8b4989d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnLoginAdmin</value>
      <webElementGuid>4f0e145d-09b8-4d72-9381-c46fc0e881b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button-submit</value>
      <webElementGuid>2a007b4d-10b2-4c0a-9f00-7222f09863dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnLoginAdmin&quot;)</value>
      <webElementGuid>da2a1716-9a8d-41d1-b067-ee3f8c1a2fa1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='btnLoginAdmin']</value>
      <webElementGuid>270f8546-7b97-4a9b-8a8a-49d2d242ae54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='logUPN3']/div/div/input[2]</value>
      <webElementGuid>df8ec2db-ff01-4922-9856-b8653b6627a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/input[2]</value>
      <webElementGuid>23355f6a-d3fe-4d5b-aa5f-d4d39fb7dff7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @name = 'btnLoginAdmin' and @id = 'btnLoginAdmin']</value>
      <webElementGuid>f1df3519-a9e5-4c48-827e-41c4ce5ae770</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
