<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Password_logUPNPassword</name>
   <tag></tag>
   <elementGuidId>e6493f21-c1e4-49b6-9e9e-6638e68e1422</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='logUPN_Password']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#logUPN_Password</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>612a170f-b4a9-43a1-8611-b25f6ab05a9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>logUPN$Password</value>
      <webElementGuid>9ca1ca05-f443-4d3f-b985-4b048cd9bb5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>457618a4-7750-404d-ac69-613605922a29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>logUPN_Password</value>
      <webElementGuid>93d1bfcf-1a9c-443c-806c-62b757004c4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>textbox-small</value>
      <webElementGuid>0f02f0c2-5e65-43ef-98fd-984eab2d21d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>0589ca58-223b-4822-9cb9-f3e4f8e61df4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;logUPN_Password&quot;)</value>
      <webElementGuid>a1ae9b6d-b2b0-49b8-8941-5a5ed4fa9df7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='logUPN_Password']</value>
      <webElementGuid>b1ac17dd-8e55-4e36-97a4-8dcc4402b1fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='logUPN']/tbody/tr/td/div/div[2]/input</value>
      <webElementGuid>92b7de9b-99fd-417b-bfe2-edaeab84900b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/input</value>
      <webElementGuid>00a1c513-8132-4bd9-a0cf-16ecaef60229</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'logUPN$Password' and @type = 'password' and @id = 'logUPN_Password']</value>
      <webElementGuid>886792b7-7071-4b90-9c1e-f2f565e7d306</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
