<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h1_Documentos</name>
   <tag></tag>
   <elementGuidId>abb78bed-2d13-42d1-8a72-18aade92b975</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ContentPlaceHolder1_dvPanelManuales']/div/div/div/h1</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>h1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>888be087-e048-4dd6-829e-9267c3ff3291</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Documentos</value>
      <webElementGuid>c65d0631-fbef-4366-bbd1-9f4b9b40103a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ContentPlaceHolder1_dvPanelManuales&quot;)/div[@class=&quot;container&quot;]/div[@class=&quot;row form-group&quot;]/div[@class=&quot;col-sm-12 col-md-12&quot;]/h1[1]</value>
      <webElementGuid>fc3737ed-caf7-4772-aeba-79a5897708f4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ContentPlaceHolder1_dvPanelManuales']/div/div/div/h1</value>
      <webElementGuid>836b9aab-c0e4-461d-b287-b387ee6701ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='GARCIA RODRIGUEZ TYLER OSCAR'])[1]/following::h1[1]</value>
      <webElementGuid>2c4cb066-5be7-48f4-ac33-8516808967ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Portal Dirección'])[1]/following::h1[1]</value>
      <webElementGuid>503d9e28-dedf-499b-8188-d0234500c81a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Manual del Módulo de Tramites'])[1]/preceding::h1[1]</value>
      <webElementGuid>9db14fa5-cce0-46b0-bfa1-acaf771b4d00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Manual del Módulo de Gestión de Desarrollo de la Docencia'])[1]/preceding::h1[1]</value>
      <webElementGuid>bd50eea9-8a06-4af9-9291-8ea073607e36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Documentos']/parent::*</value>
      <webElementGuid>e1b612ee-4a6e-4c59-8dd9-47ed823ed910</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1</value>
      <webElementGuid>7d31710c-0597-47f5-937b-77d0081fe392</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[(text() = 'Documentos' or . = 'Documentos')]</value>
      <webElementGuid>b42a3bba-eeb9-4003-9f57-37267c01b90d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
