<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Ingreso_Input.Email</name>
   <tag></tag>
   <elementGuidId>613100d4-5911-4b35-9f51-c8fe35946060</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Input_Email</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Input_Email']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a08635c9-5c39-41a0-b610-db05061ded9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>b1027fa4-4a2c-4eb1-89c3-26c082738a4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Código de alumno</value>
      <webElementGuid>c32c51dc-9e63-46db-a354-7e501acbe9f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c2d6e8ea-f567-4e3b-9aff-834da8c1fbd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>ff8a9bf1-57c0-4020-aae8-4c2f666059d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The Email field is required.</value>
      <webElementGuid>357d70a9-c876-4c48-a1dd-81c8735ab634</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Input_Email</value>
      <webElementGuid>eaf35bb0-ac83-4d54-8a55-d4b85cd26fd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Input.Email</value>
      <webElementGuid>41a4ca1b-bec4-4fbd-977f-d36496d763b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Input_Email&quot;)</value>
      <webElementGuid>09dbac65-f045-40c7-8307-701fcb0fcd6b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Input_Email']</value>
      <webElementGuid>805a08cd-f9d8-4d0c-87b2-13711458d8fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>f62d53eb-f003-4e3f-925f-bc225cb303de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Código de alumno' and @type = 'text' and @id = 'Input_Email' and @name = 'Input.Email']</value>
      <webElementGuid>d754f7d8-3dac-4044-be94-51f92e4b3a52</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
