<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h1_Perfil del alumno -  JONATHAN MICHAEL SO_1e31d7</name>
   <tag></tag>
   <elementGuidId>540c7760-9c8c-445d-86ba-d5b0f129a41a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='title-panel']/h1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>70e85aa5-cf37-4ba1-b3fe-8a3d0da23572</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Perfil del alumno -  JONATHAN MICHAEL SOLIER/PRADO (N00034693)</value>
      <webElementGuid>02edb265-4735-4755-ac6a-ead484dd66a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;title-panel&quot;)/h1[1]</value>
      <webElementGuid>f3fccf7a-085e-4467-880d-b0b455fca7fe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='title-panel']/h1</value>
      <webElementGuid>3c6dc914-9dc1-4706-94f0-b3580aa3f93a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Aviso de privacidad de Ellucian'])[1]/following::h1[1]</value>
      <webElementGuid>754faec3-1b77-42b0-a647-0a51535d1eb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Perfil del alumno'])[2]/following::h1[1]</value>
      <webElementGuid>510a93df-fa68-4bfe-bb1a-54c8258d7c60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Periodo:'])[1]/preceding::h1[1]</value>
      <webElementGuid>96ae9472-f2af-4cb7-af78-3dfc34a24610</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Horas globales:'])[1]/preceding::h1[1]</value>
      <webElementGuid>604bb991-1744-4868-b11b-3fbe4141a6b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1</value>
      <webElementGuid>37a5ce42-ee1e-4707-9dcd-65b571f3ba46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[(text() = 'Perfil del alumno -  JONATHAN MICHAEL SOLIER/PRADO (N00034693)' or . = 'Perfil del alumno -  JONATHAN MICHAEL SOLIER/PRADO (N00034693)')]</value>
      <webElementGuid>84b2b147-2d40-41cb-9130-97adba65553a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
